<h1 style="text-align: center;">Re: Far</h1>
<h2 style="text-align: center;">Aimer</h2>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">Kami, yubi, koe, manazashi, nokumuri</p>
<p style="text-align: center;">naze kana mada subete ga koko ni aru</p>
<p style="text-align: center;">koishisawa ai wo shita,</p>
<p style="text-align: center;">itoshisawa nani ni naretta kana</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">"genki de itte ne"</p>
<p style="text-align: center;">"soro soro iku ne"</p>
<p style="text-align: center;">kotoba wa itsumo&nbsp;</p>
<p style="text-align: center;">yaku ni wa tatanai</p>
<p style="text-align: center;">deatta koto ga machigai dattara</p>
<p style="text-align: center;">sou, say your little pray for you and me</p>
<p style="text-align: center;">sonna uta wa mou utawanai</p>
<p style="text-align: center;">tokimetta kuu gatsu no yoru dakara,</p>
<p style="text-align: center;">anata no wasurekata ne oshiete</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">kasameta hoho tenohira</p>
<p style="text-align: center;">mata koe,</p>
<p style="text-align: center;">sayonara demo subete wa</p>
<p style="text-align: center;">koko ni aru</p>
<p style="text-align: center;">namanurui kaze ga fueta mada sukoshi</p>
<p style="text-align: center;">natsu wa tsuzuku no kana</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">hitoge no kietta, kaisatuguchi de</p>
<p style="text-align: center;">kietta senaka wo, sagashi tsuzukitetta</p>
<p style="text-align: center;">sugita kisetsu ga, mou kunai nara</p>
<p style="text-align: center;">sou, no more cry and dry my eyes tada</p>
<p style="text-align: center;">hoshi ga kirei de nakanai to kimetta</p>
<p style="text-align: center;">hitori no kaeri michi namida ga tomaranai</p>
<p style="text-align: center;">ne doushite</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">"genki de itte ne"</p>
<p style="text-align: center;">henji wa nakute</p>
<p style="text-align: center;">kotoba wa itsumo yaku ni wa tattanai</p>
<p style="text-align: center;">sayonara anata</p>
<p style="text-align: center;">sayonara watashi</p>
<p style="text-align: center;">sou, say your little pray for you and me</p>
<p style="text-align: center;">sonna uta wa mou utawanai tokimetta&nbsp;</p>
<p style="text-align: center;">kuu gatsu no yuru dakara</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">anata no wasurekata, ne oshiete~</p>